name: presensi_hetian
version: 0.1.0
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  firebase_core: ^2.16.0
  firebase_auth: 4.10.0
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  get_cli: ^1.8.1
  get: ^4.6.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

